import React, { useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AiOutlineStar } from 'react-icons/ai'
import { BiCaretRightCircle } from 'react-icons/bi'
import { FaTicketAlt } from 'react-icons/fa'
import { FcSpeaker } from 'react-icons/fc'
import { FiCopy } from 'react-icons/fi'

export default function Home() {
  var countDate = new Date("Aug 25, 2022 00:00:00").getTime();

  const countDown = () => {
    var now = new Date().getTime();
    var gap = countDate - now;
    var second = 1000;
    var minute = second * 60;
    var hour = minute * 60;
    var day = hour * 24;

    var d = Math.floor(gap / (day))
    var h = Math.floor((gap % (day)) / (hour))
    var m = Math.floor((gap % (hour)) / (minute))
    var s = Math.floor((gap % (minute)) / (second))

    document.getElementById('day').innerText = d
    document.getElementById('hour').innerText = h
    document.getElementById('minute').innerText = m
    document.getElementById('second').innerText = s
  }

  useEffect(() => {
    const count = setInterval(() => {
      countDown()
    }, 1000);
    return () => clearInterval(count);
  }, [])

  return (
    <div className={`bg-[#ffa500] md:px-8 py-4 px-4`}>
      <Head>
        <title>BUSD MINER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <section className="mt-10 pb-16 grid place-items-center border-b-2">
          <h1 className={`${styles.title} text-[2.5rem] lg:text-[4rem] font-bold`}>
            Welcome to the <a href="https://nextjs.org" className="text-[#0070f3]">BUSD MINER LOTTRY!</a>
          </h1>

          <p className="my-3 text-[1.25rem] md:text-[1.5rem] font-['Poppins'] text-center px-1">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem unde expedita commodi beatae vel, eveniet quae.
          </p>

          <div className="flex flex-col md:flex-row gap-6 mt-7">
            <a href="#" className="flex items-center justify-between gap-3 text-[1rem] font-semibold font-['Montserrat'] leading-6 bg-white py-2 px-4 hover:text-[#0070f3]">PLAY NOW </a>

            <a href="#" className="flex items-center justify-between gap-3 text-[1rem] font-semibold font-['Montserrat'] leading-6 border py-2 px-4  hover:text-[#0070f3]">WIN A TICKET <FaTicketAlt /></a>
          </div>
        </section>

        <section className="py-20 border-b-2">
          <img src="/images/BUSD MINER_LOGO.png" alt="" />
        </section>

        <section className="grid place-items-center mt-10">
          <div className="flex items-center gap-4">
            <div className="md:w-20 w-10 h-[1px] border-b border-b-gray-600"></div>
            <div className="font-bold text-2xl">Last Winner</div>
            <div className="md:w-20 w-10 h-[1px] border-b border-b-gray-600"></div>
          </div>

          <div className="flex items-center gap-6">
            <div className="flex items-center gap-3">
              <div className="text-red-600"><AiOutlineStar size="20px" /></div>
              <span className="text-white">0xE0*****35df</span>
            </div>

            <div><FiCopy /></div>
          </div>

          <div><strong>700 BUSD</strong></div>

          <div className="flex items-center gap-2 mt-2 mb-5 px-20">
            <div className=""><FcSpeaker size="30px" /></div>
            <div className="flex items-center">
              <marquee behavior="" direction="">
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
                <span>congrats 0x34d***sg32 won $2, 440 | </span>
              </marquee>
            </div>
          </div>

          <p align="center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur.</p>

          <a href="#" className="mt-5 flex items-center justify-between gap-3 text-[1rem] font-semibold font-['Montserrat'] leading-6 bg-white py-2 px-4 hover:text-[#0070f3]">PLAY NOW </a>
        </section>

        <section className="grid place-items-center mt-8">
          <div className="countdown flex justify-center gap-2 md:gap-10 mt-[50px] pb-10 w-full overflow-auto">
            <div className="flex flex-col justify-center items-center w-[80px] lg:w-[130px]">
              <div id="day" className="w-full bg-[#333] text-white text-[3rem] lg:text-[5rem] py-3 text-center ">NA</div>
              <div className="w-full bg-[#ff0] text-[#333] text-center py-2 px-4 ">Days</div>
            </div>
            <div className="flex flex-col justify-center items-center w-[80px] lg:w-[130px]">
              <div id="hour" className="w-full bg-[#333] text-white text-[3rem] lg:text-[5rem] py-3 text-center ">NA</div>
              <div className="w-full bg-[#ff0] text-[#333] text-center py-2 px-4 ">Hours</div>
            </div>
            <div className="flex flex-col justify-center items-center w-[80px] lg:w-[130px]">
              <div id="minute" className="w-full bg-[#333] text-white text-[3rem] lg:text-[5rem] py-3 text-center ">NA</div>
              <div className="w-full bg-[#ff0] text-[#333] text-center py-2 px-4 ">Minutes</div>
            </div>
            <div className="flex flex-col justify-center items-center w-[80px] lg:w-[130px]">
              <div id="second" className="w-full bg-[#333] text-white text-[3rem] lg:text-[5rem] py-3 text-center ">NA</div>
              <div className="w-full bg-[#ff0] text-[#333] text-center py-2 px-4 ">Seconds</div>
            </div>
          </div>

          <h1 className="mt-5 text-3xl">Total ticket left <span className="py-1 px-2 bg-white font-bold">20</span></h1>

          <p className="md:text-xl text-base font-bold mt-5">Top deposited price: <span>$7, 000.49</span></p>

          <div className="flex gap-5 my-5 px-3 lg:px-[25%]">
            <div className="w-[5px] border-l-[3px] border-[#fff]"></div>
            <p className="mt-5">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis hic esse reiciendis recusandae molestias ab consequuntur ratione iure voluptate impedit. Inventore error eum nisi aliquam. Magnam autem nulla beatae.</p>
          </div>

          <div className="mt-5 flex flex-col md:flex-row items-center gap-3">
            <a href="#" className="flex items-center justify-between gap-3 text-[1rem] font-semibold font-['Montserrat'] leading-6 bg-white py-1 px-3 hover:text-[#0070f3]">Buy Ticket </a>

            <a href="#" className="hover:text-[#0070f3]">Refer to earn free ticket</a>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>Powered by <a href="tel:8112659304" className="font-bold">BINANCE MINERS</a></div>
        </a>
      </footer>
    </div>
  )
}
